name: SmallBusinessApp
options:
  bundleIdPrefix: com.majdinagi
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
settings:
  base:
    SWIFT_VERSION: 5.0
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
targets:
  SmallBusinessApp:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: SmallBusinessApp/Sources
      - path: SmallBusinessApp/Resources
        buildPhase: resources
    entitlements:
      path: SmallBusinessApp/SmallBusinessApp.entitlements
      properties:
        com.apple.developer.applesignin:
          - Default
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: HQDDMSV8AR
        PRODUCT_BUNDLE_IDENTIFIER: com.majdinagi.SmallBusinessApp
        INFOPLIST_KEY_CFBundleDisplayName: HireLocal
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UIStatusBarStyle: UIStatusBarStyleDefault
        INFOPLIST_KEY_LSApplicationCategoryType: public.app-category.business
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        TARGETED_DEVICE_FAMILY: 1,2
    scheme:
      testTargets: []
